### ISSUE TITLE
Hebrew labels show up as gibberish

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#18]
Hebrew labels show up as gibberish.
![screenshot 241](https://cloud.githubusercontent.com/assets/1942312/19741869/225a16e6-9bcb-11e6-8a07-05c31cc7dfb8.png)

They show fine in EPANET 2:
![image](https://cloud.githubusercontent.com/assets/1942312/19741955/8f561d76-9bcb-11e6-82cd-3cfd30d5fc70.png)

Attached is a sample file for testing
[Net1.inp.zip](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/554269/Net1.inp.zip)

**Comment by MarkGrayRESPEC** [comment]
On my computer, when I load this sample file these labels show up looking like the same gibberish in EPANET 2 and in the new EPANET-UI. Installing the Hebrew language pack has not helped.

I don't see any label font specified in the example inp file. I imagine EPANET 2 uses your default system font for labels when it does not have font hints. Maybe your default system font includes these characters and mine does not? What is your default system font? (Note: we plan to make a wiki page describing how to make a translation for the UI, but that is a separate question from the map labeling.)

**Comment by eladsal** [comment]
The INP doesn't have fonts for lables. Only the binary input file of EPANET 2 saves labels fonts. I'm not sure what you mean by "system fonts", where do you want me to look?

If you are asking about my languages installed here they are (my Windows UI is in English):

![screenshot 244](https://cloud.githubusercontent.com/assets/1942312/19868506/046f4d56-9fb1-11e6-814d-be1cd81ef0c4.png)

Yes, translation is a different thing but probably we should talk about Internationalization (i18n) which is a wider issue.

**Comment by MarkGrayRESPEC** [comment]
I now have the same Language settings as you with English first and Hebrew second and am still seeing the same gibberish in both EPANET 2.0 (About window says Build 2.00.12) and MTP 3. I tried hard-coding the font of the labels to David so I am sure the font has the required characters, but it is still not displaying the labels as Hebrew.
Does EPANET 2 correctly display these labels for you when the project is loaded from the .inp or only from the .net? There is a way to store font information in the .inp after the label text, but it looks like EPANET 2 did not write those fields when exporting this example. (We also do not yet try to use these font hints in the new UI.)

**Comment by eladsal** [comment]
Yes, EPANET 2.0 shows the Hebrew fonts when loaded from the INP file (EPANET didn't save the font info in the INP file). Here are some more settings on my machine:

![screenshot 245](https://cloud.githubusercontent.com/assets/1942312/19871602/49350dba-9fbe-11e6-8c22-99f9916b3dad.png)

![screenshot 246](https://cloud.githubusercontent.com/assets/1942312/19871606/4d905a7c-9fbe-11e6-85d3-8503f86a62f5.png)

**Comment by MarkGrayRESPEC** [comment]
I have just made a change that allows map label objects in SWMM and EPANET user interface to have unicode text instead of just ASCII. This text is encoded in UTF-8 in the project .inp file.

To test this feature:
1. get the latest version of the EPANET or SWMM UI (must be a version after MTP 3r3, not yet available as of today)
2. open an existing project
3. switch your keyboard to another language (hopefully you already know how to do this if you want this feature)
4. add a label using the "T" toolbar button
5. type your label text and press OK
6. verify that the label is displayed correctly on the map and in the list of labels
7. verify that saving the project to a .inp file and loading it again works

Note: This change is not compatible with the example Net1.inp attached to this issue.
