### ISSUE TITLE
SWMM MTP 3 does not display links for this input file

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/SWMM-EPANET_User_Interface#20]
These are examples of input files that only imports the nodes and not the links.  I do have other files from SWMM5 QA/QC and the basic list of files installed with SWMM 5 that do  work. 

[My2016.zip](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/562712/My2016.zip)
![swmm5-ui_linksdonotseemtobeimported](https://cloud.githubusercontent.com/assets/5599939/19868736/ba08cb42-9f7f-11e6-8996-8daffea0e8de.png)

**Comment by MarkGrayRESPEC** [comment]
I have successfully reproduced this problem in the development version, so we should be able to find a fix.

**Comment by MarkGrayRESPEC** [comment]
This issue was caused by a problem with processing comments between items in a section that is indexed by name. These comments were added directly to the list between the items, but comments did not have names to index and therefore caused an error when they were added.
Now a comment between items is stored as a comment on the item below it in the file. This fixes the issue. Traversing a list of items is now also more straightforward since there are now only the type of item expected instead of also having comments as separate items.
The provided examples bring up a new issue of not properly writing the LOSSES section when saving .inp.
