### ISSUE TITLE
EPANET_MTP4r2_ Report-Menu_Full..._Low

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#221]
If no model is loaded, i.e., UI just opened, the UI opens a Windows Explorer browser to locate folder for downloading full status report, HOWEVER NO MODEL IS LOADED. 

If program is newly opened then user is prompted that the model must be run first, i.e., the UI retains previously run results after closing.

If there was a previously run project and then closed by clicking "New", previous runs full status report will be saved.

**Comment by rjanke20** [comment]
Similar problems are observed with the UI under Report/Graph and Report/Table.

**Comment by TongZhai** [comment]
@rjanke20 What I see is that clicking 'New' will sever the linkage to previously opened project's results, a message for model needing to be run first will be displayed when accessing a newly loaded model, which is the expected behavior. I am not certain if this is somewhat unclear or causing confusion, if yes, then we need to have a more detailed discussion about exactly what the issue was.

**Comment by PaulDudaRESPEC** [comment]
This issue appears to be resolved in the current development version.
