### ISSUE TITLE
ENsetpatternvalue sets zero value (passing a reference rather than value)

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#253]
ENsetpatternvalue sets zero value (passing a reference rather than value)

Version: EPANET MTP4r2 (master branch)
Priority: High

**Comment by eladsal** [comment]
@ehsanMa86 is this a GUI issue or a problem with the engine API call?

**Comment by ehsanMa86** [comment]
fValue2 = ctypes.c_float()
fValue2.value = fValue
self.errcode = self.ENlib.ENset...value(iIndex, iCode, fValue2)

is the solution to fix it.

**Comment by michaeltryby** [comment]
@ehsanMa86 How about issuing that fix in a PR? That would be even better!

**Comment by ehsanMa86** [comment]
@michaeltryby sure I will. Thanks!

**Comment by michaeltryby** [comment]
@ehsanMa86 have you made any progress on that PR?

**Comment by TongZhai** [comment]
@michaeltryby ok, the function in question takes in 3 arguments as below
```
* iIndex  = time pattern index
* iPeriod = time pattern period
* fValue  = pattern multiplier
```
the proposed ctypes conversion is for '`fValue`', what about the two integer arguments, ctypes has `c_int32` and `c_int64` (actually a couple others), I suppose we would use `c_int64`. In fact, let's use this one as a guide for the 4 other similar issues posted by @ehsanMa86. Could you help confirm the necessity for this update, especially since the API works in its current state.

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
