### ISSUE TITLE
EPANET MTP2 run error

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#4]
Hi,

I have installed EPANET MTP2 on top of MTP1 (Windows 8.1 64 bits). Installation went fine.
When running Net1.inp I got some errors. First 305 and then 434.
Attached are the INP file (with txt extension) the errors screenshots and the report file for the run.

Thanks!

[Net1.inp.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/317729/Net1.inp.txt)
[Net1_status.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/317731/Net1_status.txt)
![error 305](https://cloud.githubusercontent.com/assets/1942312/16106395/b886f2e8-339c-11e6-897e-051e017b2999.png)
![error 434](https://cloud.githubusercontent.com/assets/1942312/16106396/bc02517e-339c-11e6-947c-c63a05c4f957.png)

**Comment by MarkGrayRESPEC** [comment]
This looks like the error we have seen when this package is installed in Program Files or Program Files (x86). While we work on a solution to this problem, we recommend installing in a different location. If you are getting this error when it is installed somewhere else, please let us know where because that could help us find a solution.


Mark Gray

________________________________

**Comment by eladsal** [comment]
@MarkGrayRESPEC I have installed the program in the root directory and it now runs. Thanks.
