### ISSUE TITLE
EPANET_VIEW_MENU

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#50]
Map Dimensions - Seems incomplete, upper left coordinates are missing. Features under this item do not seem to work properly.
Query – nothing happens.  Shouldn’t the user be given a query box?
Overview – Similarly, nothing happens.
Objects and Legends have SWMM components
Map Options - Nothing happens

**Comment by PaulDudaRESPEC** [comment]
Map Dimensions -- I think this menu item should go away, because this now editable under 'Options:Map/Backdrop' from the project tree.

Query is not yet implemented.
Overview is not yet implemented.

Objects and Legends should be limited to only the ones relevant to the context (no rain gages in EPANET for example)

Map Options -- we've talked about having a way to edit these, but it isn't implemented yet.  When it is implemented, it will likely be from the 'Layers' tab and not here, so this can go away.

**Comment by PaulDudaRESPEC** [comment]
Removed Objects menu (SWMM feature only) and Legends:Subcatchments (SWMM-only)

**Comment by PaulDudaRESPEC** [comment]
I believe the only one of these items that is still in need of attention is the MapOverview.

**Comment by PaulDudaRESPEC** [comment]
Map Overview is now implemented
