### ISSUE TITLE
EPANET_VIEW_BACKDROP

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#52]
Backdrop – the user can “LOAD” a .bmp backdrop but it is not a backdrop, it is dislocated from the network model.  Nothing seems to happen with the "UNLOAD" feature.  It is not clear how the user would get rid of the backdrop or change it.

**Comment by PaulDudaRESPEC** [comment]
I think the Backdrop menu item should go away, because this now editable under 'Options:Map/Backdrop' from the project tree.  There may be more to do there, however, to fully implement the backdrop feature.

**Comment by rjanke20** [comment]
Pipe network is not visible. Should be able to hide backdrop.

In the old GUI, there was an option to Hide/Show the backdrop once it was loaded. This was useful when you are adding, editing pipes to make sure you’re able to get them where you want them, but also to see how the network is progressing.
--

**Comment by TongZhai** [comment]
@rjanke20 this issue is addressed by the above commit. The handling of raster base map(s) is via 'Add a raster layer' operation and all its manipulations (i.e. show/hide, removal/unload) are done in the 'Layer' tab of the UI by right click on any layer to show context menu options. Now users can add as many raster base maps as they want.
