### ISSUE TITLE
Slow results table loading

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#7]
With a large EPANET model (12K junctions) the results tables loads in about 12 seconds (64 bits, Windows 8.1, 6GB, i7). EPANET 2.12 loads it in an eye-blink.

**Comment by MarkGrayRESPEC** [comment]
The largest model in our current test suite has about 3k junctions, do you have a large test case we could use?

**Comment by eladsal** [comment]
Sure, this is network 2 of the Battle of the Water Sensor Networks.

[Example_2.zip](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/323678/Example_2.zip)

**Comment by MarkGrayRESPEC** [comment]
Thank you for this example. It is a nice addition to our testing suite.

**Comment by MarkGrayRESPEC** [comment]
The results table is now displayed in less than two seconds for this example. This update is in the dev-ui branch which will be included in the next release. This was accomplished by a combination of changes: 
In ENOutputWrapper.py, lists of nodes and links are now dictionaries for faster access.
In get_all_attributes_at_time, an argument to ENR_newOutValueArray was corrected so it only processes the number of attributes present instead of also processing extra zeroes.
The table is now displayed early after the first 20 rows are populated instead of waiting until all rows are populated.
